### ISSUE TITLE
ROADMAP: Headless Accordion

### ISSUE THREAD

**Issue by thejackshelton** [qwikifiers/qwik-ui#379]
Here are the plans for the headless `<Accordion/>` component

## Post Beta

- [ ] Direction prop, a union type with the **ltr** or **rtl** values that stand for "left to right" or "right to left". This is internationalization support for the component.
- [ ] Orientation prop, a prop that enables horizontal accordion behavior.
- [ ] Progressive enhancement - render the  accordion as static text when javascript is disabled, instead of a broken trigger.

## Planned
- [ ] bind:event support.
